addons:
  postgresql: 9.6
before_install:
  - cd code/server
dist: trusty
language: ruby
rvm:
  - 2.5.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
notifications:
  slack: pl5es:84Pa1a9D0o7hXNvlby4JeYl2
