default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: server_development


test:
  <<: *default
  database: server_test

production:
  <<: *default
  database: server_production
  username: server
password: <%= ENV['SERVER_DATABASE_PASSWORD'] %>
